INSERT INTO subcategory (id, category_id, name)
VALUES ('1', '1', 'Outerwear'),
       ('2', '1', 'Blouses, Shirts'),
       ('3', '1', 'Pants, Jeans, Shorts'),
       ('4', '1', 'Jackets, Suits'),
       ('5', '1', 'Dresses, Sundresses, Skirts'),
       ('6', '1', 'Sweaters, Sweatshirts, Jackets'),
       ('7', '1', 'T-shirts'),
       ('8', '1', 'Tracksuits'),
       ('9', '1', 'Hats, Scarves, Mittens, Gloves'),
       ('10', '1', 'Tights, Socks'),
       ('11', '1', 'Carnival Costumes'),
       ('12', '1', 'Other (Clothing)'),
       ('13', '2', 'Sneakers'),
       ('14', '2', 'Boots'),
       ('15', '2', 'Sandals, Slippers'),
       ('16', '2', 'Low Shoes, Moccasins'),
       ('17', '2', 'Other (Shoes)'),
       ('18', '3', 'Lego & Constructors'),
       ('19', '3', 'Stuffed Toys'),
       ('20', '3', 'Equipment & Weapons'),
       ('21', '3', 'Dolls'),
       ('22', '3', 'Board Games'),
       ('23', '3', 'Game Sets'),
       ('24', '3', 'Puzzles'),
       ('25', '3', 'Sport'),
       ('26', '3', 'Kinder Surprise & Figures'),
       ('27', '3', 'Creation'),
       ('28', '3', 'Other (Toys)'),
       ('29', '4', 'Tables & Chairs'),
       ('30', '4', 'Beds'),
       ('31', '4', 'Mattresses'),
       ('32', '4', 'Cabinets'),
       ('33', '4', 'Children`s Beds'),
       ('34', '4', 'Chests & Dressers-changers'),
       ('35', '4', 'High Chairs'),
       ('36', '4', 'Playpen'),
       ('37', '4', 'Interior Items'),
       ('38', '4', 'Toy Baskets'),
       ('39', '4', 'Other (Children`s Furniture)'),
       ('40', '5', 'Bicycles'),
       ('41', '5', 'Sled'),
       ('42', '5', 'Prams'),
       ('43', '5', 'Runbikes'),
       ('44', '5', 'Walkers'),
       ('45', '5', 'Scooters'),
       ('46', '5', 'Skateboards'),
       ('47', '5', 'Roller Skates'),
       ('48', '5', 'Electric Transport'),
       ('49', '5', 'Protection & Accessories'),
       ('50', '5', 'Other (Vehicles For Children)'),
       ('51', '6', 'Clothing For Babies'),
       ('52', '6', 'Stroll'),
       ('53', '6', 'Growth'),
       ('54', '6', 'Children`s Room'),
       ('55', '6', 'Products For Sleeping'),
       ('56', '6', 'Safety'),
       ('57', '6', 'Bathing & Toilet'),
       ('58', '6', 'Other (Kids Until Year)'),
       ('59', '7', 'Textbooks'),
       ('60', '7', 'Children`s Literature'),
       ('61', '7', 'Coloring Pages'),
       ('62', '7', 'Fairy Tales'),
       ('63', '7', 'Useful Literature For Parents'),
       ('64', '7', 'Other (Books)'),
       ('65', '8', 'Other');
