export const types = {
	ADD_ME_INPUT_VALUE: 'ADD_ME_INPUT_VALUE',
	ADD_PHONE_INPUT_VALUE: 'ADD_PHONE_INPUT_VALUE',
	ADD_PHONE: 'ADD_PHONE',
	DELETE_PHONE: 'DELETE_PHONE',
	ADD_CHILDREN_INPUT_VALUE: 'ADD_CHILDREN_INPUT_VALUE',
	ADD_CHILD: 'ADD_CHILD',
	DELETE_CHILD: 'DELETE_CHILD',
	FILL_USER_INFO_SYNC: 'FILL_USER_INFO_SYNC',

	FETCH_USER_INFO_ASYNC: 'FETCH_USER_INFO_ASYNC',
	PUT_USER_INFO_ASYNC: 'PUT_USER_INFO_ASYNC',
};
