export const types = {
	CHANGE_INPUT_VALUE: 'CHANGE_INPUT_VALUE',
	CHANGE_PHONE_INPUT_VALUE: 'CHANGE_PHONE_INPUT_VALUE',
	ADD_PHONE: 'ADD_PHONE',
	DELETE_PHONE: 'DELETE_PHONE',
	CHANGE_CHILDREN_INPUT_VALUE: 'CHANGE_CHILDREN_INPUT_VALUE',
	CHOOSE_GENDER: 'CHOOSE_GENDER',
	ADD_CHILD: 'ADD_CHILD',
	DELETE_CHILD: 'DELETE_CHILD',
	CHANGE_LANG_PROFILE_ERRORS: 'CHANGE_LANG_PROFILE_ERRORS',
	CHANGE_PERMISSION_PROFILE: 'CHANGE_PERMISSION_PROFILE',
	CHANGE_PERMISSION_CHILDREN: 'CHANGE_PERMISSION_CHILDREN',

	FILL_USER_INFO_SYNC: 'FILL_USER_INFO_SYNC',
	FETCH_USER_INFO_ASYNC: 'FETCH_USER_INFO_ASYNC',
	PUT_USER_INFO_ASYNC: 'PUT_USER_INFO_ASYNC',

	USER_POST_CHILDREN_ASYNC: 'USER_POST_CHILDREN_ASYNC',
	USER_PUT_CHILDREN_ASYNC: 'USER_PUT_CHILDREN_ASYNC',
	USER_DELETE_CHILDREN_ASYNC: 'USER_DELETE_CHILDREN_ASYNC',
	PUT_RECEIVED_POST_CHILDREN: 'PUT_RECEIVED_POST_CHILDREN',
	PUT_RECEIVED_PUT_CHILDREN: 'PUT_RECEIVED_PUT_CHILDREN'

};
