export const route = {
  home: '/',
  addAdv: 'add-good',
  login: '/login',
  signUp: 'sign',
  userInfo: 'user',
  myProfile: 'profile',
  myFavorite: 'favorites',
  mySettings: 'settings',
  exit: 'exit',
  productPage: '/product-page/:id',
  prevProductPage: '/product-page',
  oauthSuccess: '/oauth-success',
  noMatch: '*',
};
