export const types = {
	CHOOSE_LANGUAGE: 'CHOOSE_LANGUAGE',
	CHANGE_CHECKBOX: 'CHANGE_CHECKBOX',
	CHANGE_INPUT_AUTH:'CHANGE_INPUT_AUTH',
	CLEAR_VALUE_LOGIN:'CLEAR_VALUE_LOGIN',
	CLEAR_VALUE_SIGNUP:'CLEAR_VALUE_SIGNUP',
	TOGGLE_DISABLE_BUTTON_LOG:'TOGGLE_DISABLE_BUTTON_LOG',
	TOGGLE_DISABLE_BUTTON_REG:'TOGGLE_DISABLE_BUTTON_REG',
	PUT_TOKEN_LOCALSTORAGE: 'PUT_TOKEN_LOCALSTORAGE',


	POST_AUTH_LOGIN_ASYNC:'POST_AUTH_LOGIN_ASYNC',
	POST_AUTH_REGISTER_ASYNC:'POST_AUTH_REGISTER_ASYNC',
};