export const types = {
	CHOOSE_LANGUAGE: 'CHOOSE_LANGUAGE',
	CHANGE_CHECKBOX: 'CHANGE_CHECKBOX',
	CHANGE_INPUT_AUTH:'CHANGE_INPUT_AUTH',
	CLEAR_VALUE_LOGIN:'CLEAR_VALUE_LOGIN',
	CLEAR_VALUE_SIGNUP:'CLEAR_VALUE_SIGNUP',
};