const en = {
  auth: {
    login: 'log In',
    signUp: 'Sign Up',
    logEmail: 'Enter your E-mail or login',
    logPassword: 'Enter your password',
    regEmail: 'Enter your E-mail',
    regLogin: 'Enter your login',
    regPassword: 'Enter your password',
    regConfirm: 'Confirm password',
    remember: 'Remember me',
    noLogin: "Can't login?",
    agreement:
      '* I agree to the terms of use of the service, as well as to the transfer and processing of my data. I confirm that I am of legal age and responsible for posting ads.',
  },
  popup: {
    serverResponse: 'Server response',
  },
  errors: {
    requireField: 'Field is required',
    invalidEmailFormat: 'Invalid mail format',
    max129: 'Must be no more than 129 characters',
    min2: 'Must be at least 2 characters',
    max50: 'Must be no more than 50 characters',
    altCodeMatch: "Shouldn't have Alt code",
    min8: 'Must be at least 8 characters',
    max30: 'Must be no more than 30 characters',
    passwordMatch: 'Large and small Latin letters and numbers',
    passwordMismatch: 'Password mismatch',
    noSpace: 'There should be no spaces',
    nameMatch: 'Any letters',
    phoneMatch: 'Invalid phone format',
    passwordIdentical: 'The password matches the current one',
    emailIdentical: 'Email is the same as the old one',
    emailNotIdentical: 'Email does not match',
  },
  panel: {
    myActivity: 'My activity',
    myProfile: 'My profile',
    myFavorite: 'My favorite',
    mySettings: 'Settings',
    myExit: 'Exit',
  },
  ownInfo: {
    aboutMe: 'About me',
    firstName: 'Name:',
    lastName: 'Last name:',
    phone: 'Phone:',
    children: 'Children',
    dateOfBirth: 'Date of birth:',
    gender: 'Gender:',
    boy: 'Boy',
    girl: 'Girl',
    unselected: 'Unselected',
  },
  settings: {
    changePassword: 'Change password',
    currentPassword: 'Current password:',
    newPassword: 'New password:',
    confirmPassword: 'Repeat password:',
    changeEmail: 'Change E-MaiL',
    oldEmail: 'Old E-Mail:',
    newEmail: 'New E-Mail:',
    confirmEmail: 'Repeat E-Mail:',
    remove: 'Remove account',
    describe:
      'Attention! After deleting your account, your profile will be completely removed from the site directory and many functions will no longer be available. You can change contact details and phone numbers in the menu section',
    profile: 'Profile',
  },
  exit: {
    question: 'Leave?',
    text: 'You can’t leave messages and add ads!',
    exit: 'exit',
  },
  button: {
    addAdv: 'Add new advertisement',
    addField: 'Add field',
    removeField: 'Remove field',
    saveChanges: 'Save changes',
    enter: 'Enter',
    look: 'View',
    save: 'SAVE',
    saveEmail: 'SAVE EMAIL',
    remove: 'REMOVE ACCOUNT',
  },
  header: {
    about: 'About the project',
    goodness: 'Good deals',
    myOffice: 'Personal area',
    categories: 'Categories',
    iSearch: 'Search',
    clothes: 'clothes',
    shoes: 'shoes',
    toys: 'toys',
    vehicles: 'Transport for children',
    furniture: "children's furniture",
    babies: 'babies to 1 year',
    books: 'books',
    another: 'another',
  },
  footer: {
    rules: 'Safe deal rules',
    charity: 'Charity organisations',
    questions: 'Frequently asked Questions',
    protect: 'All rights reserved',
  },
  fourOhFour: {
    noPage: 'The page does not exist!',
    mainPage: 'To the main',
    backPage: 'Back',
  },
  somethingBad: {
    error: 'Error! What should we do the next?',
  },
  product: {
    categories: 'Categories',
    blueTitle: 'You may also be interested in',
    dateOfAdv: 'Date of publication',
    cityOfAdv: 'City',
    phoneOfAdv: 'Phone',
    changesTo: 'Changes to',
    description: 'Description',
    size: 'Size',
    age: 'Age',
    season: 'Season',
    sex: 'Sex',
    button: 'Offers for exchange',
    checkInUl: 'your offers',
  },
  mainPage: {
    question: 'Have a lot accumulated of',
    questionBold: "children's things?",
    answerFirstPart: 'Just',
    answerBold: 'register',
    answerSecondPart: 'and post your',
    answerThirdPart: 'advertisement!',
    changeBold: 'Trade',
    changeFirstPart: 'with other users',
    changeSecondPart: 'for something cool and',
    changeThirdPart: 'useful!',
    blueText: 'Current offers',
    blueSearch: 'Advanced Search',
    blueSlideSubtitle: 'Huge selection of',
    blueSlideTitle: 'Toys',
    greenSlideSubtitle: 'Variety for children and teenagers of',
    greenSlideTitle: 'Clothes',
    yellowSlideSubtitle: 'Everything for',
    yellowSlideTitle: 'Infants',
    pinkSlideSubtitle: "Lots of children's",
    pinkSlideTitle: 'Furniture',
    lilacSlideSubtitle: 'Variety for children and teenagers of',
    lilacSlideTitle: 'Shoes',
    orangeSlideSubtitle: "Children's",
    orangeSlideTitle: 'Transport',
    helpTitle: "There are no other people's children!",
    helpName: 'Obminyashka',
    helpText:
      'cooperates with volunteer organizations for\n' +
      '         all over Ukraine! You can help too! Give your unnecessary things, they\n' +
      '         will end up in orphanages and orphanages!',
    helpButton: 'I want to help children!',
  },
};

export default en;
