const en = {
  auth: {
    login: 'log In',
    signUp: 'Sign Up',
    logEmail: 'Enter your E-mail or login',
    logPassword: 'Enter your password',
    regEmail: 'Enter your E-mail',
    regLogin: 'Enter your login',
    regPassword: 'Enter your password',
    regConfirm: 'Confirm password',
    remember: 'Remember me',
    noLogin: "Can't login?",
    agreement:
      '* I agree to the terms of use of the service, as well as to the transfer and processing of my data. I confirm that I am of legal age and responsible for posting ads.',
  },
  popup: {
    serverResponse: 'Server response',
    errorTitle: 'Error',
    errorTitleSize: 'Pay attention',
    errorTitleSubCategory: 'Attention / Information',
    notEmptyInput: 'At least one field is required.',
    selectCategory: 'Initially you need to select a category',
    addedFile: "The photo you've just added is already exist.",
    pictureSelection: 'Select a photo with one of the supported extensions',
    sizeFile: 'Your photo total size',
    selectFile: 'Select a photo up to 10 MB total size',
    noSaveMore:
      'The maximum capacity of photos to be stored can be up to 10 pcs',
    selectSize: 'Dimensions are only available for Clothing and Shoes',
    addChildren: 'Children added successfully',
  },
  errors: {
    minPhoto: 'Minimum 1 photo',
    requireField: 'Field is required',
    invalidEmailFormat: 'Invalid mail format',
    min2: 'Minimum of 2 characters',
    min3: 'Minimum of 3 characters',
    min8: 'Minimum of 8 characters',
    max30: 'Maximum 30 characters',
    max40: 'Maximum 40 characters',
    max50: 'Maximum 50 characters',
    max129: 'Maximum 129 characters',
    max200: 'Maximum 200 characters',
    max255: 'Maximum 255 characters',
    altCodeMatch: "Shouldn't have Alt code",
    passwordMatch: 'Large and small Latin letters and numbers',
    passwordMismatch: 'Password mismatch',
    noSpace: 'There should be no spaces',
    nameMatch: 'Any letters',
    phoneMatch: 'Invalid phone format',
    passwordIdentical: 'The password matches the current one',
    emailIdentical: 'Email is the same as the old one',
    emailNotIdentical: 'Email does not match',
  },
  panel: {
    myActivity: 'My activity',
    myProfile: 'My profile',
    myFavorite: 'My favorite',
    mySettings: 'Settings',
    myExit: 'Exit',
  },
  ownInfo: {
    aboutMe: 'About me',
    firstName: 'Name:',
    lastName: 'Last name:',
    phone: 'Phone:',
    children: 'Children',
    dateOfBirth: 'Date of birth:',
    gender: 'Gender:',
    boy: 'Boy',
    girl: 'Girl',
    unselected: 'Unselected',
    chooseData: 'First you need to choose a date of birth',
  },
  settings: {
    changePassword: 'Change password',
    currentPassword: 'Current password:',
    newPassword: 'New password:',
    confirmPassword: 'Repeat password:',
    changeEmail: 'Change E-MaiL',
    oldEmail: 'Old E-Mail:',
    newEmail: 'New E-Mail:',
    confirmEmail: 'Repeat E-Mail:',
    remove: 'Remove account',
    describe:
      'Attention! After deleting your account, your profile will be completely removed from the site directory and many functions will no longer be available. You can change contact details and phone numbers in the menu section',
    profile: 'Profile',
  },
  exit: {
    question: 'Leave?',
    text: 'You can’t leave messages and add ads!',
    exit: 'exit',
  },
  button: {
    addAdv: 'Add new advertisement',
    addField: 'Add field',
    removeField: 'Remove field',
    saveChanges: 'Save changes',
    enter: 'Enter',
    googleOAuth: 'Enter',
    look: 'View',
    save: 'SAVE',
    saveEmail: 'SAVE EMAIL',
    remove: 'REMOVE ACCOUNT',
    back: 'Back',
  },
  header: {
    about: 'About the project',
    goodness: 'Good deals',
    myOffice: 'Personal area',
    categories: 'Categories',
    iSearch: 'Search',
    clothes: 'clothes',
    shoes: 'shoes',
    toys: 'toys',
    vehicles: 'Transport for children',
    furniture: "children's furniture",
    babies: 'babies to 1 year',
    books: 'books',
    another: 'another',
  },
  footer: {
    rules: 'Safe deal rules',
    charity: 'Charity organisations',
    questions: 'Frequently asked Questions',
    protect: 'All rights reserved',
  },
  fourOhFour: {
    noPage: 'The page does not exist!',
    mainPage: 'To the main',
    backPage: 'Back',
  },
  somethingBad: {
    error: 'Error! What should we do the next?',
  },
  product: {
    categories: 'Categories',
    blueTitle: 'You may also be interested in',
    dateOfAdv: 'Date of publication',
    cityOfAdv: 'City',
    phoneOfAdv: 'Phone',
    changesTo: 'Changes to',
    description: 'Description',
    size: 'Size',
    age: 'Age',
    season: 'Season',
    sex: 'Sex',
    button: 'Offers for exchange',
    checkInUl: 'your offers',
  },
  mainPage: {
    question: 'Have a lot accumulated of',
    questionBold: "children's things?",
    answerFirstPart: 'Just',
    answerBold: 'register',
    answerSecondPart: 'and post your',
    answerThirdPart: 'advertisement!',
    changeBold: 'Trade',
    changeFirstPart: 'with other users',
    changeSecondPart: 'for something cool and',
    changeThirdPart: 'useful!',
    blueText: 'Current offers',
    blueSearch: 'Advanced Search',
    blueSlideSubtitle: 'Huge selection of',
    blueSlideTitle: 'Toys',
    greenSlideSubtitle: 'Variety for children and teenagers of',
    greenSlideTitle: 'Clothes',
    yellowSlideSubtitle: 'Everything for',
    yellowSlideTitle: 'Infants',
    pinkSlideSubtitle: "Lots of children's",
    pinkSlideTitle: 'Furniture',
    lilacSlideSubtitle: 'Variety for children and teenagers of',
    lilacSlideTitle: 'Shoes',
    orangeSlideSubtitle: "Children's",
    orangeSlideTitle: 'Transport',
    helpTitle: "There are no other people's children!",
    helpName: 'Obminyashka',
    helpText:
      'cooperates with volunteer organizations for\n' +
      '         all over Ukraine! You can help too! Give your unnecessary things, they\n' +
      '         will end up in orphanages and orphanages!',
    helpButton: 'I want to help children!',
  },
  addAdv: {
    chooseSection: 'Choose a section',
    category: 'Category',
    subcategory: 'Subcategory',
    headline: 'Headline',
    selectCategory: 'Select a category',
    selectSubcategory: 'Select a subcategory',
    readyForOffers: 'I will consider your offer',
    exchange: 'Exchange',
    whatChange: 'What do you want to exchange?',
    enterPhrase: 'enter the phrase, and then press Enter',
    placeholderChange: 'Enter what you want to exchange',
    options: 'Characteristics',
    age: 'Age',
    sex: 'Sex',
    size: 'Size',
    season: 'Season',
    describeTitle: "Your item's description",
    describeText: 'Describe your item: defects, usage patterns, etc.',
    districtKyiv: 'Kyivska',
    district: 'Area',
    city: 'Locality',
    uploadDescription: 'Upload few photos of your item',
    firstUploadDescription:
      'The first uploaded photo will be the title photo of the item',
    photosUploaded: 'Photos uploaded',
    from: 'from',
    preview: 'Preview',
    cancel: 'Cancel everything',
    chooseSize: 'Choose a size',
  },
  categories: {
    Clothing: 'Clothing',
    Shoes: 'Shoes',
    Toys: 'Toys',
    'Children`S Furniture': 'Kids Furniture',
    'Vehicles For Children': 'Vehicles For Children',
    'Kids Until Year': 'Kids Until Year',
    Books: 'Books',
    Other: 'Other',
    Outerwear: 'Outerwear',
    'Blouses, Shirts': 'Blouses, Shirts',
    'Pants, Jeans, Shorts': 'Pants, Jeans, Shorts',
    'Jackets, Suits': 'Jackets, Suits',
    'Dresses, Sundresses, Skirts': 'Dresses, Sundresses, Skirts',
    'Sweaters, Sweatshirts, Jackets': 'Sweaters, Sweatshirts, Jackets',
    'T-shirts': 'T-shirts',
    Tracksuits: 'Tracksuits',
    'Hats, Scarves, Mittens, Gloves': 'Hats, Scarves, Mittens, Gloves',
    'Tights, Socks': 'Tights, Socks',
    'Carnival Costumes': 'Carnival Costumes',
    'Other (Clothing)': 'Other (Clothing)',

    Sneakers: 'Sneakers',
    Boots: 'Boots',
    'Sandals, Slippers': 'Sandals, Slippers',
    'Low Shoes, Moccasins': 'Low Shoes, Moccasins',
    'Other (Shoes)': 'Other (Shoes)',

    'Lego & Constructors': 'Lego & Constructors',
    'Stuffed Toys': 'Stuffed Toys',
    'Equipment & Weapons': 'Equipment & Weapons',
    Dolls: 'Dolls',
    'Board Games': 'Board Games',
    'Game Sets': 'Game Sets',
    Puzzles: 'Puzzles',
    Sport: 'Sport',
    'Kinder Surprise & Figures': 'Kinder Surprise & Figures',
    Creation: 'Creation',
    'Other (Toys)': 'Other (Toys)',

    'Tables & Chairs': 'Tables & Chairs',
    Beds: 'Beds',
    Mattresses: 'Mattresses',
    Cabinets: 'Cabinets',
    'Children`s Beds': 'Children`s Beds',
    'Chests & Dressers-changers': 'Chests & Dressers-changers',
    'High Chairs': 'High Chairs',
    Playpen: 'Playpen',
    'Interior Items': 'Interior Items',
    'Toy Baskets': 'Toy Baskets',
    'Other (Children`s Furniture)': 'Other (Children`s Furniture)',

    Bicycles: 'Bicycles',
    Sled: 'Sled',
    Prams: 'Prams',
    Runbikes: 'Runbikes',
    Walkers: 'Walkers',
    Scooters: 'Scooters',
    Skateboards: 'Skateboards',
    'Roller Skates': 'Roller Skates',
    'Electric Transport': 'Electric Transport',
    'Protection & Accessories': 'Protection & Accessories',
    'Other (Vehicles For Children)': 'Other (Vehicles For Children)',

    'Clothing For Babies': 'Clothing For Babies',
    Stroll: 'Stroll',
    Growth: 'Growth',
    'Children`s Room': 'Children`s Room',
    'Products For Sleeping': 'Products For Sleeping',
    Safety: 'Safety',
    'Bathing & Toilet': 'Bathing & Toilet',
    'Other (Kids Until Year)': 'Other (Kids Until Year)',

    Textbooks: 'Textbooks',
    'Children`s Literature': 'Children`s Literature',
    'Coloring Pages': 'Coloring Pages',
    'Fairy Tales': 'Fairy Tales',
    'Useful Literature For Parents': 'Useful Literature For Parents',
    'Other (Books)': 'Other (Books)',
  },
  genderEnum: {
    MALE: 'For boys',
    FEMALE: 'For girls',
    UNSELECTED: 'Boy/Girl',
  },
  seasonEnum: {
    WINTER: 'Winter',
    SUMMER: 'Summer',
    ALL_SEASONS: 'All seasons',
    DEMI_SEASON: 'Demi-season',
  },
};

export default en;
