const ru = {
  auth: {
    login: 'Вход',
    signUp: 'Регистрация',
    logEmail: 'Введите ваш E-mail или логин',
    logPassword: 'Введите ваш пароль',
    regEmail: 'Введите ваш E-mail',
    regLogin: 'Введите ваш Логин',
    regPassword: 'Введите ваш пароль',
    regConfirm: 'Повторите пароль',
    remember: 'Запомнить меня',
    noLogin: 'Не можете войти?',
    agreement:
      '* Я соглашаюсь с правилами использования сервиса, а также с передачей и обработкой моих данных. Я подтверждаю своё совершеннолетие и ответственность за размещение объявлений.',
  },
  popup: {
    serverResponse: 'Ответ от сервера',
    errorTitle: 'Ошибка',
    notEmptyInput: 'Требуется хотя бы одно поле заполнено.',
  },
  errors: {
    requireField: 'Поле обязательно',
    invalidEmailFormat: 'Неверный формат почты',
    max129: 'Должно быть не более 129 символов',
    min2: 'Должно быть не менее 2 символов',
    max50: 'Должно быть не более 50 символов',
    altCodeMatch: 'Не должно быть Alt code',
    min8: 'Должно быть не менее 8 символов',
    max30: 'Должно быть не более 30 символов',
    passwordMatch: 'Большие и малые латинские буквы и цифры',
    passwordMismatch: 'Пароли не совпадают',
    noSpace: 'Не должно быть пробелов',
    nameMatch: 'Любые буквы',
    phoneMatch: 'Неверный формат телефона',
    passwordIdentical: 'Пароль совпадает с текущим',
    emailIdentical: 'Email совпадает со старым',
    emailNotIdentical: 'Email не совпадает',
  },
  panel: {
    myActivity: 'Моя активность',
    myProfile: 'Мой профиль',
    myFavorite: 'Избранное',
    mySettings: 'Настройки',
    myExit: 'Выход',
  },
  ownInfo: {
    aboutMe: 'О себе',
    firstName: 'Имя:',
    lastName: 'Фамилия:',
    phone: 'Телефон:',
    children: 'Дети',
    dateOfBirth: 'Дата рождения:',
    gender: 'Пол:',
    boy: 'Мальчик',
    girl: 'Девочка',
    unselected: 'Не выбрано',
  },
  settings: {
    changePassword: 'Сменить пароль',
    currentPassword: 'Текущий пароль:',
    newPassword: 'Новый пароль:',
    confirmPassword: 'Повторите пароль:',
    changeEmail: 'Сменить E-Mail',
    oldEmail: 'Старый E-Mail:',
    newEmail: 'Новый E-Mail:',
    confirmEmail: 'Повторите E-Mail:',
    remove: 'Удалить аккаунт',
    describe:
      'Внимание! После удаления учетной записи, ваш профиль будет полностью удален из каталога сайта и многие функции перестанут быть' +
      ' доступными. Вы можете поменять контактные данные и номера телефонов в разделе меню',
    profile: 'Профиль',
  },
  exit: {
    question: 'Выйти?',
    text: 'Вы не сможете оставлять сообщения и добавлять объявления!',
    exit: 'Выход',
  },
  button: {
    addAdv: 'Добавить объявление',
    addField: 'Добавить поле',
    removeField: 'Удалить поле',
    saveChanges: 'Сохранить изменения',
    enter: 'Войти',
    look: 'Смотреть',
    save: 'СОХРАНИТЬ',
    saveEmail: 'СОХРАНИТЬ EMAIL',
    remove: 'УДАЛИТЬ АККАУНТ',
  },
  header: {
    about: 'О проекте',
    goodness: 'Доброе дело',
    myOffice: 'Мой кабинет',
    categories: 'Категории',
    iSearch: 'Я ищу',
    clothes: 'Одежда',
    shoes: 'Обувь',
    toys: 'Игрушки',
    vehicles: 'Транспорт для детей',
    furniture: 'Детская мебель',
    babies: 'Малыши до года',
    books: 'Книги',
    another: 'Другое',
  },
  footer: {
    rules: 'Правила безопасной сделки',
    charity: 'Благотворительные организации',
    questions: 'Часто задаваемые вопросы',
    protect: 'Все права защищены',
  },
  fourOhFour: {
    noPage: 'Страница не существует!',
    mainPage: 'На главную',
    backPage: 'Назад',
  },
  somethingBad: {
    error: 'Ошибка! Что будем делать?',
  },
  product: {
    categories: 'Категории',
    blueTitle: 'Вас так же могут заинтересовать',
    dateOfAdv: 'Дата публикации',
    cityOfAdv: 'Город',
    phoneOfAdv: 'Телефон',
    changesTo: 'Меняет на',
    description: 'Описание',
    size: 'Размер',
    age: 'Возраст',
    season: 'Сезон',
    sex: 'Пол',
    button: 'Предложить обмен',
    checkInUl: 'ваши предложения',
  },
  mainPage: {
    question: 'Накопилось много',
    questionBold: 'детских вещей?',
    answerFirstPart: 'Просто',
    answerBold: 'зарегистрируйся',
    answerSecondPart: 'и размести',
    answerThirdPart: 'объявление!',
    changeBold: 'Обменяйтесь',
    changeFirstPart: 'с другими пользователями',
    changeSecondPart: 'на что-то клёвое и',
    changeThirdPart: 'полезное!',
    blueText: 'Текущие предложения',
    blueSearch: 'Расширенный поиск',
    blueSlideSubtitle: 'Огромный выбор',
    blueSlideTitle: 'Игрушек',
    greenSlideSubtitle: 'Разнообразие детской и подростковой',
    greenSlideTitle: 'Одежды',
    yellowSlideSubtitle: 'Всё для',
    yellowSlideTitle: 'Малышей',
    pinkSlideSubtitle: 'Множество детской',
    pinkSlideTitle: 'Мебели',
    lilacSlideSubtitle: 'Разнообразие детской и подростковой',
    lilacSlideTitle: 'Обуви',
    orangeSlideSubtitle: 'Детский',
    orangeSlideTitle: 'Транспорт',
    helpTitle: 'Чужих детей не бывает!',
    helpName: 'Обменяшка',
    helpText:
      'сотрудничает с волонтерскими организациями по\n' +
      '        всей Украине! Ты тоже можешь помочь! Отдай свои ненужные вещи, они\n' +
      '        попадут в детские дома и приюты!',
    helpButton: 'я хочу помочь детям!',
  },
  productEnums: {
    gender: {
      male: 'Мужской',
      female: 'Женский',
      unselected: 'Не выбран',
    },
    season: {
      winter: 'Зима',
      summer: 'Лето',
      allSeasons: 'Все сезоны',
      demiSeason: 'Демисезон',
    },
  },
};

export default ru;
