const ua = {
  auth: {
    login: 'Вхід',
    signUp: 'Реєстрація',
    logEmail: 'Введіть ваш E-mail або логін',
    logPassword: 'Введіть Ваш пароль',
    regEmail: 'Введіть ваш E-mail',
    regLogin: 'Введіть ваш логін',
    regPassword: 'Введіть Ваш пароль',
    regConfirm: 'Повторіть пароль',
    remember: "Запам'ятати мене",
    noLogin: 'Чи не можете увійти?',
    agreement:
      '* Я погоджуюсь з правилами використання сервісу, а також з передачею і обробкою моїх даних. Я підтверджую своє повноліття і відповідальність за розміщення оголошень.',
  },
  popup: {
    serverResponse: 'Відповідь від сервера',
    errorTitle: 'Помилка',
    errorTitleSize: 'Зверніть увагу',
    errorTitleSubCategory: 'Увага / Інформація',
    notEmptyInput: 'Потрібно хоча б одне поле заповнене.',
    selectCategory: 'Початково потрібно вибрати категорію',
    addedFile: 'Щойно додане фото вже існує в списку обраних',
    pictureSelection: 'Пожалуйста, выберите фото согласно указанным форматам',
    sizeFile: 'Розмір вашого фото',
    selectFile: 'Виберіть фото обсягом до 10 МБ.',
    noSaveMore: 'Ви не можете мати більше ніж 10 збережених фото.',
    selectSize: 'Розміри доступні виключно для Одягу та Взуття',
    addChildren: 'Діти успішно додані',
  },
  errors: {
    minPhoto: 'Мінімум 1 фото',
    requireField: "Поле обов'язково",
    invalidEmailFormat: 'Невірний формат пошти',
    min2: 'Повинно бути не менше 2 символів',
    min3: 'Повинно бути не менше 3 символів',
    min8: 'Повинно бути не менше 8 символів',
    max30: 'Повинно бути не більше 30 символів',
    max40: 'Повинно бути не більше 40 символів',
    max50: 'Повинно бути не більше 50 символів',
    max129: 'Повинно бути не більше 129 символів',
    max200: 'Повинно бути не більше 200 символів',
    max255: 'Повинно бути не більше 255 символів',
    altCodeMatch: 'Не повинно бути Alt code',
    passwordMatch: 'Великі і малі латинські букви і цифри',
    passwordMismatch: 'Паролі не співпадають',
    noSpace: 'Не повинно бути пробілів',
    nameMatch: 'Будь-які літери',
    phoneMatch: 'Невірний формат телефону',
    passwordIdentical: 'Пароль збігається з поточним',
    emailIdentical: 'Email збігається зі старим',
    emailNotIdentical: 'Email не збігається',
  },
  panel: {
    myActivity: 'Моя активність',
    myProfile: 'Мій профіль',
    myFavorite: 'Вибране',
    mySettings: 'Налаштування',
    myExit: 'Вихід',
  },
  ownInfo: {
    aboutMe: 'Про себе',
    firstName: "Iм'я:",
    lastName: 'Прізвище:',
    phone: 'Телефон:',
    children: 'Діти',
    dateOfBirth: 'Дата народження:',
    gender: 'Стать:',
    boy: 'Хлопчик',
    girl: 'Дівчинка',
    unselected: 'Не вибрано',
    chooseData: 'Спочатку треба вибрати дату народження',
  },
  settings: {
    changePassword: 'Змінити пароль',
    currentPassword: 'Поточний пароль:',
    newPassword: 'Новий пароль:',
    confirmPassword: 'Повторіть пароль:',
    changeEmail: 'Змінити E-MaiL',
    oldEmail: 'Старий E-Mail:',
    newEmail: 'Новий E-Mail:',
    confirmEmail: 'Повторіть E-Mail:',
    remove: 'Видалити акаунт',
    describe:
      'Увага! Після видалення облікового запису, ваш профіль буде повністю видалений з каталогу сайту і багато функцій перестануть бути доступними. Ви можете поміняти контактні дані та номери телефонів в розділі меню',
    profile: 'Профіль',
  },
  exit: {
    question: 'Вийти?',
    text: 'Ви не зможете залишати повідомлення і додавати оголошення!',
    exit: 'вихід',
  },
  button: {
    addAdv: 'Додати оголошення',
    addField: 'Додати поле',
    removeField: 'Видалити поле',
    saveChanges: 'Зберегти зміни',
    enter: 'Увійти',
    googleOAuth: 'Увійти',
    look: 'Дивитись',
    save: 'ЗБЕРЕГТИ',
    saveEmail: 'ЗБЕРЕГТИ EMAIL',
    remove: 'ВИДАЛИТИ АКАУНТ',
    back: 'Назад',
  },
  header: {
    about: 'Про проект',
    goodness: 'Добра справа',
    myOffice: 'Мій кабінет',
    categories: 'Категорії',
    iSearch: 'Я шукаю',
    clothes: 'Одяг',
    shoes: 'Взуття',
    toys: 'іграшки',
    vehicles: 'Транспорт для дітей',
    furniture: 'Дитячі меблі',
    babies: 'Малюки до року',
    books: 'Книги',
    another: 'інше',
  },
  footer: {
    rules: 'Правила безпечної угоди',
    charity: 'Благодійні організації',
    questions: 'Часті питання',
    protect: 'Всі права захищені',
  },
  fourOhFour: {
    noPage: 'Сторінку не знайдено!',
    mainPage: 'На головну',
    backPage: 'Назад',
  },
  somethingBad: {
    error: 'Помилка! Що будемо робити?',
  },
  product: {
    categories: 'Категорії',
    blueTitle: 'Вас також можуть зацікавити',
    dateOfAdv: 'Дата публікації',
    cityOfAdv: 'Місто',
    phoneOfAdv: 'Телефон',
    changesTo: 'Обмінює на',
    description: 'Опис',
    size: 'Розмір',
    age: 'Вік',
    season: 'Сезон',
    sex: 'Стать',
    button: 'Запропонувати обмін',
    checkInUl: 'ваші пропозиції',
  },
  mainPage: {
    question: 'Накопичилося багато ',
    questionBold: 'дитячих речей?',
    answerFirstPart: 'Просто',
    answerBold: 'зареєструйся',
    answerSecondPart: 'і розмісти',
    answerThirdPart: 'оголошення!',
    changeBold: 'Обміняйтесь',
    changeFirstPart: 'з іншими користувачами',
    changeSecondPart: 'на щось кльове і',
    changeThirdPart: 'корисне!',
    blueText: 'Поточні пропозиції',
    blueSearch: 'Розширений пошук',
    blueSlideSubtitle: 'Величезний вибір',
    blueSlideTitle: 'Іграшок',
    greenSlideSubtitle: 'Різноманітність дитячого та підліткового',
    greenSlideTitle: 'Одягу',
    yellowSlideSubtitle: 'Все для',
    yellowSlideTitle: 'Малюків',
    pinkSlideSubtitle: 'Безліч дитячих',
    pinkSlideTitle: 'Меблів',
    lilacSlideSubtitle: 'Різноманітність дитячого та підліткового',
    lilacSlideTitle: 'Взуття',
    orangeSlideSubtitle: 'Дитячий',
    orangeSlideTitle: 'Транспорт',
    helpTitle: 'Чужих дітей не буває!',
    helpName: 'Обміняшка',
    helpText:
      'співпрацює з волонтерськими організаціями по\n' +
      '         всій Україні! Ти теж можеш допомогти! Віддай свої непотрібні речі, вони\n' +
      '         потраплять до дитячих будинків і притулків!',
    helpButton: 'я хочу допомогти дітям!',
  },
  addAdv: {
    chooseSection: 'Виберіть розділ',
    category: 'Категорія',
    subcategory: 'Підкатегорія',
    headline: 'Заголовок оголошення',
    selectCategory: 'Виберіть категорію',
    selectSubcategory: 'Виберіть підкатегорію',
    readyForOffers: 'Розгляну Вашу пропозицію',
    exchange: 'Обмін',
    whatChange: 'На що бажаєте обмінятися?',
    enterPhrase: 'введіть фразу, а потім натисніть Enter',
    placeholderChange: 'Введіть на що бажаєте обмінятися',
    options: 'Характеристики',
    age: 'Вік',
    sex: 'Стать',
    size: 'Розмір',
    season: 'Сезон',
    describeTitle: 'Опис',
    describeText: 'Опишіть Вашу річ: деффекти, особливості використання, тощо',
    districtKyiv: 'Київська',
    district: 'Область',
    city: 'Населений пункт',
    uploadDescription: 'Завантажте фотографії ваших речей',
    firstUploadDescription: 'Перше фото стане обкладинкою картки товару',
    photosUploaded: 'Завантажено фотографій',
    from: 'з',
    preview: 'Попередній перегляд',
    cancel: 'Скасувати все',
    chooseSize: 'Оберіть розмір',
  },
  categories: {
    Clothing: 'Одяг',
    Shoes: 'Взуття',
    Toys: 'Іграшки',
    'Children`S Furniture': 'Дитячі меблі',
    'Vehicles For Children': 'Транспортні засоби для дітей',
    'Kids Until Year': 'Діти до року',
    Books: 'Книги',
    Other: 'Інше',

    Outerwear: 'Верхній одяг',
    'Blouses, Shirts': 'Блузки, сорочки',
    'Pants, Jeans, Shorts': 'Штани, джинси, шорти',
    'Jackets, Suits': 'Куртки, костюми',
    'Dresses, Sundresses, Skirts': 'Сукні, сарафани, спідниці',
    'Sweaters, Sweatshirts, Jackets': 'Светри, кофти, куртки',
    'T-shirts': 'Футболки',
    Tracksuits: 'Спортивні костюми',
    'Hats, Scarves, Mittens, Gloves': 'Шапки, шарфи, рукавиці, рукавички',
    'Tights, Socks': 'Колготки, шкарпетки',
    'Carnival Costumes': 'Карнавальні костюми',
    'Other (Clothing)': 'Інше (одяг)',

    Sneakers: 'Кросівки',
    Boots: 'Чоботи',
    'Sandals, Slippers': 'Босоніжки, тапочки',
    'Low Shoes, Moccasins': 'Низьке взуття, мокасини',
    'Other (Shoes)': 'Інше (взуття)',

    'Lego & Constructors': 'Конструктори та Лего',
    'Stuffed Toys': "М'які іграшки",
    'Equipment & Weapons': 'Обладнання та зброя',
    Dolls: 'Ляльки',
    'Board Games': 'Настільні ігри',
    'Game Sets': 'Ігрові набори',
    Puzzles: 'Головоломки',
    Sport: 'Спорт',
    'Kinder Surprise & Figures': 'Кіндер-сюрприз і фігурки',
    Creation: 'Творчість',
    'Other (Toys)': 'Інше (іграшки)',

    'Tables & Chairs': 'Столи та Стільці',
    Beds: 'Ліжка',
    Mattresses: 'Матраци',
    Cabinets: 'Шафи',
    'Children`s Beds': 'Дитячі ліжка',
    'Chests & Dressers-changers': 'Скрині та комоди',
    'High Chairs': 'Високі крісла',
    Playpen: 'Манеж',
    'Interior Items': 'Предмети інтер’єру',
    'Toy Baskets': 'Кошики для іграшок',
    'Other (Children`s Furniture)': 'Інше (дитячі меблі)',

    Bicycles: 'Велосипеди',
    Sled: 'Санки',
    Prams: 'Коляски',
    Runbikes: 'Бігові велосипеди',
    Walkers: 'Ходунки',
    Scooters: 'Скутери',
    Skateboards: 'Скейтборди',
    'Roller Skates': 'Роликові ковзани',
    'Electric Transport': 'Електротранспорт',
    'Protection & Accessories': 'Захист та аксесуари',
    'Other (Vehicles For Children)': 'Інше (транспорт для дітей)',

    'Clothing For Babies': 'Одяг для немовлят',
    Stroll: 'Прогулянка',
    Growth: 'Зростання',
    'Children`s Room': 'Дитяча кімната',
    'Products For Sleeping': 'Вироби для сну',
    Safety: 'Безпека',
    'Bathing & Toilet': 'Купання та туалет',
    'Other (Kids Until Year)': 'Інше (діти до року)',

    Textbooks: 'Підручники',
    'Children`s Literature': 'Дитяча література',
    'Coloring Pages': 'Розмальовки',
    'Fairy Tales': 'Казки',
    'Useful Literature For Parents': 'Корисна література для батьків',
    'Other (Books)': 'Інше (книги)',
  },
  genderEnum: {
    MALE: 'Хлопчакові',
    FEMALE: 'Дівочі',
    UNSELECTED: 'Хлопчик/Дівчинка',
  },
  seasonEnum: {
    WINTER: 'Зима',
    SUMMER: 'Літо',
    ALL_SEASONS: 'Всі сезони',
    DEMI_SEASON: 'Демісезон',
  },
};

export default ua;
