name: Obminyashka

on:
  push:
    branches: [ github-action ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          check-latest: true

      - name: Run mvn clean package
        env:
          NPM_AUTH_TOKEN: ${{ secrets.OBMINYASHKA_COMPONENT_SECRET }}
        run: mvn clean package --quiet
      - name: Transfer artifact to the server via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          DB_PASSWORD: ${{ secrets.OBMINYASHKA_DATABASE_PASSWORD_SECRET }}
          SSL_PASSWORD: ${{ secrets.OBMINYASHKA_CERTIFICATE_PASSWORD_SECRET }}
          JWT_TOKEN_SECRET: ${{ secrets.OBMINYASHKA_TOKEN_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.OBMINYASHKA_ID_GOOGLE_API_SECRET }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.OBMINYASHKA_GOOGLE_SECRET }}
          SENDGRID_API_KEY: ${{ secrets.OBMINYASHKA_SENDGRID_SECRET }}
        with:
          REMOTE_HOST: ${{ secrets.OBMINYASHKA_SERVER_HOST_SECRET }}
          REMOTE_USER: ${{ secrets.OBMINYASHKA_SERVER_USERNAME_SECRET }}
          SSH_PRIVATE_KEY: ${{ secrets.OBMINYASHKA_SSH_PRIVATE_KEY }}
          TARGET: "/home/$REMOTE_TARGET/target/"
          SCRIPT_BEFORE: ls
          SCRIPT_AFTER: java -jar ./target/*.jar --server.ssl.key-store=~/CGE-service/keystore.p12 --logging.file.name=~/CGE-service/LogFile.log

