name: Obminyashka

on:
  push:
    branches: [ github-action ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          check-latest: true
          cache: maven

      - name: Run build with Maven
        run: mvn --batch-mode --update-snapshots package --quiet
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./target/space.obminyashka-*.jar
          retention-days: 7

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    permissions:
      contents: read
      packages: write
    steps:
      - name: Upload Artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
      - name: Deploy over SSH
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./space.obminyashka-*.jar
          remote: target
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
      - name: Run commands
        env:
          DB_PASSWORD: ${{ secrets.OBMINYASHKA_DATABASE_PASSWORD_SECRET }}
          SSL_PASSWORD: ${{ secrets.OBMINYASHKA_CERTIFICATE_PASSWORD_SECRET }}
          JWT_TOKEN_SECRET: ${{ secrets.OBMINYASHKA_TOKEN_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.OBMINYASHKA_ID_GOOGLE_API_SECRET }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.OBMINYASHKA_GOOGLE_SECRET }}
          SENDGRID_API_KEY: ${{ secrets.OBMINYASHKA_SENDGRID_SECRET }}
        run: |
          whoami
          ls -a
#          rsync -r ./target/ ${{ secrets.OBMINYASHKA_SERVER_USERNAME_SECRET }}@${{ secrets.OBMINYASHKA_SERVER_HOST_SECRET }}:target/
#          java -jar ./target/*.jar --server.ssl.key-store=~/CGE-service/keystore.p12 --logging.file.name=~/CGE-service/LogFile.log
