name: Obminyashka

on:
  push:
    branches: [ github-action ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          check-latest: true

      - name: Run mvn clean install
        env:
          NPM_AUTH_TOKEN: ${{ secrets.OBMINYASHKA_COMPONENT_SECRET }}
        run: mvn clean install
      - name: Build jar file
        run: java -jar ./target/*.jar --spring.datasource.password='${{secrets.OBMINYASHKA_DATABASE_PASSWORD_SECRET}}'
                                      --server.ssl.key-store-password='${{secrets.OBMINYASHKA_CERTIFICATE_PASSWORD_SECRET}}'
                                      --app.jwt.secret='${{secrets.OBMINYASHKA_TOKEN_SECRET}}'
                                      --server.ssl.key-store=/home/obmen/CGE-service/keystore.p12
                                      --spring.security.oauth2.client.registration.google.client-id='${{secrets.OBMINYASHKA_ID_GOOGLE_API_SECRET}}'
                                      --spring.security.oauth2.client.registration.google.client-secret='${{secrets.OBMINYASHKA_GOOGLE_SECRET}}'
                                      --logging.file.name=/home/obmen/CGE-service/LogFile.log
                                      --spring.sendgrid.api-key='${{secrets.OBMINYASHKA_SENDGRID_SECRET}}'

