name: Obminyashka

on:
  push:
    branches: [ github-action ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          check-latest: true
          cache: maven

      - name: Run build with Maven
        run: mvn --batch-mode --update-snapshots package --quiet
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: ./target/space.obminyashka-*.jar
          retention-days: 7

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    permissions:
      contents: read
      packages: write
    steps:
      - name: Upload Artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
      - name: Deploy over SSH
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .
          remote: target/space.obminyashka-latest.jar
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

  run:
    runs-on: ubuntu-latest
    needs: [ build, deploy ]
    environment: production
    steps:
      - name: Run artefact
        uses: appleboy/ssh-action@v0.1.8
        env:
          DB_PASSWORD: ${{ secrets.OBMINYASHKA_DATABASE_PASSWORD_SECRET }}
          SSL_PASSWORD: ${{ secrets.OBMINYASHKA_CERTIFICATE_PASSWORD_SECRET }}
          JWT_TOKEN_SECRET: ${{ secrets.OBMINYASHKA_TOKEN_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.OBMINYASHKA_ID_GOOGLE_API_SECRET }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.OBMINYASHKA_GOOGLE_SECRET }}
          SENDGRID_API_KEY: ${{ secrets.OBMINYASHKA_SENDGRID_SECRET }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            java -jar ./target/*.jar 
              --spring.datasource.password='${{env.DB_PASSWORD}}' \
              --server.ssl.key-store-password='${{env.SSL_PASSWORD}}' \
              --app.jwt.secret='${{env.JWT_TOKEN_SECRET}}' \
              --server.ssl.key-store=~/CGE-service/keystore.p12 \
              --spring.security.oauth2.client.registration.google.client-id='${{env.GOOGLE_CLIENT_ID}' \
              --spring.security.oauth2.client.registration.google.client-secret='${{env.GOOGLE_CLIENT_SECRET}' \
              --logging.file.name=~/CGE-service/LogFile.log \
              --spring.sendgrid.api-key='${{env.SENDGRID_API_KEY}'
