name: Obminyashka

on:
  push:
    branches: [ github-action ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          check-latest: true
          cache: maven

      - name: Run mvn clean package
        run: mvn --batch-mode --update-snapshots package --quiet

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.OBMINYASHKA_SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.OBMINYASHKA_KNOWN_HOSTS }}
          if_key_exists: replace
      - name: Deploy with rsync
        uses: BuildPC/rsync-with-ssh-github-actions@master
        with:
          key: ${{secrets.OBMINYASHKA_SSH_PRIVATE_KEY}}
          host: ${{secrets.OBMINYASHKA_SERVER_HOST_SECRET }}
          port: 22
          user: ${{secrets.OBMINYASHKA_SERVER_USERNAME_SECRET }}
          destination: ~/target/

      - name: Run commands
        env:
          DB_PASSWORD: ${{ secrets.OBMINYASHKA_DATABASE_PASSWORD_SECRET }}
          SSL_PASSWORD: ${{ secrets.OBMINYASHKA_CERTIFICATE_PASSWORD_SECRET }}
          JWT_TOKEN_SECRET: ${{ secrets.OBMINYASHKA_TOKEN_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.OBMINYASHKA_ID_GOOGLE_API_SECRET }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.OBMINYASHKA_GOOGLE_SECRET }}
          SENDGRID_API_KEY: ${{ secrets.OBMINYASHKA_SENDGRID_SECRET }}
        run: |
          whoami
          ls -a
          java -jar ./target/*.jar --server.ssl.key-store=~/CGE-service/keystore.p12 --logging.file.name=~/CGE-service/LogFile.log
