name: Obminyashka

on:
  push:
    branches: [ github-action ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          check-latest: true

      - name: Run mvn clean package
        env:
          NPM_AUTH_TOKEN: ${{ secrets.OBMINYASHKA_COMPONENT_SECRET }}
        run: mvn clean package --quiet
      - shell: bash
        env:
          DB_PASSWORD: ${{ secrets.OBMINYASHKA_DATABASE_PASSWORD_SECRET }}
          SSL_PASSWORD: ${{ secrets.OBMINYASHKA_CERTIFICATE_PASSWORD_SECRET }}
          JWT_TOKEN_SECRET: ${{ secrets.OBMINYASHKA_TOKEN_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.OBMINYASHKA_ID_GOOGLE_API_SECRET }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.OBMINYASHKA_GOOGLE_SECRET }}
          SENDGRID_API_KEY: ${{ secrets.OBMINYASHKA_SENDGRID_SECRET }}
        run: java -jar ./target/*.jar --spring.datasource.password="$DB_PASSWORD"
          --server.ssl.key-store-password="$SSL_PASSWORD"
          --app.jwt.secret="$JWT_TOKEN_SECRET"
          --server.ssl.key-store=/home/obmen/CGE-service/keystore.p12
          --spring.security.oauth2.client.registration.google.client-id="$GOOGLE_CLIENT_ID"
          --spring.security.oauth2.client.registration.google.client-secret="$GOOGLE_CLIENT_SECRET"
          --logging.file.name=/home/obmen/CGE-service/LogFile.log
          --spring.sendgrid.api-key="$SENDGRID_API_KEY"

