name: Obminyashka

on:
  push:
    branches: [ github-action ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          check-latest: true

      - name: Check variable
        run: echo "${{ secrets.OBMINYASHKA_COMPONENT_SECRET}}"

      - name: Build with Maven
        env:
          NPM_AUTH_TOKEN: ${{ secrets.OBMINYASHKA_COMPONENT_SECRET }}
        run: mvn clean install