name: Java CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - debug
  schedule:
    # every Monday at 3 PM UTC (20:00 Kyiv Time)
    - cron: '0 15 * * MON'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true
      - name: Run build with Maven
        run: mvn --batch-mode --update-snapshots package jacoco:prepare-agent
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          repo-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./target/space.obminyashka-*.jar
          retention-days: 7

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    permissions:
      contents: read
      packages: write
    steps:
      - name: Upload Artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact
      - name: Deploy over SSH
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .
          remote: target
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

  run:
    runs-on: ubuntu-latest
    needs: [ build, deploy ]
    environment: production
    steps:
      - name: Run artefact
        uses: appleboy/ssh-action@v1.2.0
        env:
          DB_PASSWORD: ${{ secrets.OBMINYASHKA_DATABASE_PASSWORD_SECRET }}
          SSL_PASSWORD: ${{ secrets.OBMINYASHKA_CERTIFICATE_PASSWORD_SECRET }}
          SSL_PATH: ${{ secrets.OBMINYASHKA_CERTIFICATE_PATH }}
          JWT_TOKEN_SECRET: ${{ secrets.OBMINYASHKA_TOKEN_SECRET }}
          GOOGLE_CLIENT_ID: ${{ secrets.OBMINYASHKA_ID_GOOGLE_API_SECRET }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.OBMINYASHKA_GOOGLE_SECRET }}
          SENDGRID_API_KEY: ${{ secrets.OBMINYASHKA_SENDGRID_SECRET }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            export DB_PASSWORD='${{ env.DB_PASSWORD }}'
            export SSL_PASSWORD='${{ env.SSL_PASSWORD }}'
            export SSL_PATH=${{ env.SSL_PATH }}
            export JWT_TOKEN_SECRET='${{ env.JWT_TOKEN_SECRET }}'
            export GOOGLE_CLIENT_ID='${{ env.GOOGLE_CLIENT_ID }}'
            export GOOGLE_CLIENT_SECRET='${{ env.GOOGLE_CLIENT_SECRET }}'
            export SENDGRID_API_KEY='${{ env.SENDGRID_API_KEY }}'
            kill -9 $(lsof -t -i:8443) || echo "Process was not running."
            echo "java -jar ./target/*.jar" | at now + 1 minutes

  inform:
    runs-on: ubuntu-latest
    needs: [ build, deploy, run ]
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🤖 GitHub Actions 🤖 ⏲️ scheduled deployed is 🏁COMPLETED🏁 🎉
            
            🛫 LAST DEPLOYED COMMIT 🛫
            👩‍💻 Author: ${{ github.event.commits[0].author.name}}
            🗨️ Message: ${{ github.event.commits[0].message }}
            📃 Changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
            🪜 DEPLOYED COMMITS STACK 🪜
            https://github.com/${{ github.repository }}/commits/master
